export const dbCatalogHydrocircles = [
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 1.png",
    name: "Гидроцикл BRP SeaDoo GTI 130hp SE Black Mango",
    price: 1049500,
    sale: true,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 2.png",
    name: "Гидроцикл BRP SeaDoo GTI 155hp SE Long Blue Metallic",
    price: 1100475,
    sale: false,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 3.png",
    name: "Гидроцикл BRP SeaDoo GTR 230hp STD Black / Gulfstream",
    price: 0,
    sale: true,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 4.png",
    name: "Гидроцикл BRP SeaDoo GTX 300hp LTD Liquid Metal",
    price: 1543000,
    sale: false,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 5.png",
    name: "Гидроцикл BRP SeaDoo Spark GTS 90hp Rental",
    price: 857666,
    sale: false,
  },

  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 6.png",
    name: "Гидроцикл BRP SeaDoo WAKE 230hp PRO Teal blue",
    price: 1229711,
    sale: false,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 7.png",
    name: "Гидроцикл Spark 2-UP 900 Ho Ace Pineapple ",
    price: 587440,
    sale: false,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/gidrotsikl-brp-seadoo-gti-130hp-se-blackmango-orange-73936232995706_small6 8.png",
    name: "Гидроцикл BRP Sea-doo Spark 2-UP 900 Ace Vanilla ",
    price: 0,
    sale: true,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/s-l225 1.png",
    name: "Гидроцикл BRP SeaDoo GTR 230hp X California green  ",
    price: 1323700,
    sale: false,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/s-l225 2.png",
    name: "Гидроцикл Spark 2-UP 900 Ho Ace Pineapple ",
    price: 587440,
    sale: false,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/s-l225 3.png",
    name: "Гидроцикл Spark 2-UP 900 Ho Ace Chili Pepper ",
    price: 587440,
    sale: true,
  },
  {
    id: new Date().getMilliseconds(),
    path: "/Images/hydrocircles/s-l225 4.png",
    name: "Гидроцикл Spark 3-UP 900 HO Ace IBR Blueberry ",
    price: 0,
    sale: false,
  },
];
